name: Compile New Docker Image
run-name: Compiling New Docker Image of Class Forge
on:
  push:
    paths:
      - 'Dockerfile'
jobs:
  CompileAndUploadDockerImage:
    runs-on: ubuntu-latest
    steps:
      # Clone class-forge repo locally
      - run: git clone https://github.com/mario872/class-forge
      # Log into Docker Hub
      - run: docker login -u "$username" -p "$password" && python upload-docker.py
        working-directory: ./class-forge
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Run upload-docker.py
      #- run: python upload-docker.py
      #  working-directory: ./class-forge
